#ifndef INC_SYSTEM_MCU
#define INC_SYSTEM_MCU

#ifdef __cplusplus
extern "C" {
#endif

#include <libopencm3/stm32/rcc.h>
#include "core/app.h"

/* Start of autogenerated OD types */
/* 0x6000: System MCUnull */
typedef struct system_mcu_properties {
    uint8_t parameter_count;
    char family[8];
    char board_type[10];
    uint32_t storage_index;
    uint8_t phase;
    int16_t cpu_temperature;
    uint32_t startup_time; // In milliseconds 
} system_mcu_properties_t;
/* End of autogenerated OD types */

struct system_mcu {
    actor_t *actor;
    system_mcu_properties_t *properties;
    actor_t *storage;
    const struct rcc_clock_scale *clock;
};

extern actor_class_t system_mcu_class;

/* Start of autogenerated OD accessors */
typedef enum system_mcu_properties_properties {
  SYSTEM_MCU_FAMILY = 0x01,
  SYSTEM_MCU_BOARD_TYPE = 0x02,
  SYSTEM_MCU_STORAGE_INDEX = 0x03,
  SYSTEM_MCU_PHASE = 0x04,
  SYSTEM_MCU_CPU_TEMPERATURE = 0x05,
  SYSTEM_MCU_STARTUP_TIME = 0x06
} system_mcu_properties_properties_t;

/* 0x60XX04: null */
#define system_mcu_set_phase(mcu, value) actor_set_property_numeric(mcu->actor, (uint32_t) value, sizeof(uint8_t), SYSTEM_MCU_PHASE)
#define system_mcu_get_phase(mcu) *((uint8_t *) actor_get_property_pointer(mcu->actor, &(uint8_t[sizeof(uint8_t)]{}), sizeof(uint8_t), SYSTEM_MCU_PHASE)
/* 0x60XX05: null */
#define system_mcu_set_cpu_temperature(mcu, value) actor_set_property_numeric(mcu->actor, (uint32_t) value, sizeof(int16_t), SYSTEM_MCU_CPU_TEMPERATURE)
#define system_mcu_get_cpu_temperature(mcu) *((int16_t *) actor_get_property_pointer(mcu->actor, &(uint8_t[sizeof(int16_t)]{}), sizeof(int16_t), SYSTEM_MCU_CPU_TEMPERATURE)
/* 0x60XX06: In milliseconds */
#define system_mcu_set_startup_time(mcu, value) actor_set_property_numeric(mcu->actor, (uint32_t) value, sizeof(uint32_t), SYSTEM_MCU_STARTUP_TIME)
#define system_mcu_get_startup_time(mcu) *((uint32_t *) actor_get_property_pointer(mcu->actor, &(uint8_t[sizeof(uint32_t)]{}), sizeof(uint32_t), SYSTEM_MCU_STARTUP_TIME)
/* End of autogenerated OD accessors */


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
