#ifndef CO_SPI_H
#define CO_SPI_H

#ifdef __cplusplus
extern "C" {
#endif


#include "devices/devices.h"
#include <libopencm3/stm32/spi.h>

/* Start of autogenerated OD types */
/* 0x7120: Module SPI 1
   ADC Unit used for high-volume sampling of analog signals */
typedef struct {
    int16_t disabled;
    uint8_t index;
    uint8_t dma_rx_unit;
    uint8_t dma_rx_channel;
    uint8_t dma_tx_unit;
    uint8_t dma_tx_channel;
    uint8_t ss_port;
    uint8_t ss_pin;
    uint8_t sck_port;
    uint8_t sck_pin;
    uint8_t miso_port;
    uint8_t miso_pin;
    uint8_t mosi_port;
    uint8_t mosi_pin;
} module_spi_config_t;
/* End of autogenerated OD types */

typedef struct {
    device_t *device;
    module_spi_config_t *config;
    uint32_t clock;
    uint32_t address;
} module_spi_t;

extern device_callbacks_t module_spi_callbacks;

void module_spi_send(module_spi_t *spi, uint8_t value);

/* Start of autogenerated OD accessors */
#define SUBIDX_SPI_DISABLED 0x1
#define SUBIDX_SPI_INDEX 0x2
#define SUBIDX_SPI_DMA_RX_UNIT 0x3
#define SUBIDX_SPI_DMA_RX_CHANNEL 0x4
#define SUBIDX_SPI_DMA_TX_UNIT 0x5
#define SUBIDX_SPI_DMA_TX_CHANNEL 0x6
#define SUBIDX_SPI_SS_PORT 0x7
#define SUBIDX_SPI_SS_PIN 0x8
#define SUBIDX_SPI_SCK_PORT 0x9
#define SUBIDX_SPI_SCK_PIN 0x10
#define SUBIDX_SPI_MISO_PORT 0x11
#define SUBIDX_SPI_MISO_PIN 0x12
#define SUBIDX_SPI_MOSI_PORT 0x13
#define SUBIDX_SPI_MOSI_PIN 0x14

/* End of autogenerated OD accessors */

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CO_SPI_H */