/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.0-51-g2d9b1ad

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY !!!!
********************************************************************************

    File info:
        File Names:   Base_F4.h; Base_F4.c
        Project File: Base_F4.xdd
        File Version: 1

        Created:      1/3/2022 7:32:53 PM
        Created By:   
        Modified:     1/12/2022 6:11:30 PM
        Modified By:  

    Device Info:
        Vendor Name:  
        Vendor ID:    
        Product Name: Base F4
        Product ID:   

        Description:  
*******************************************************************************/

#ifndef Base_F4_H
#define Base_F4_H
/*******************************************************************************
    Counters of OD objects
*******************************************************************************/
#define Base_F4_CNT_HB_CONS 0
#define Base_F4_CNT_NMT 0
#define Base_F4_CNT_EM 0
#define Base_F4_CNT_SDO_SRV 0
#define Base_F4_CNT_SDO_CLI 0
#define Base_F4_CNT_TIME 0
#define Base_F4_CNT_SYNC 0
#define Base_F4_CNT_RPDO 0
#define Base_F4_CNT_TPDO 0
#define Base_F4_CNT_GFC 0
#define Base_F4_CNT_SRDO 0


/*******************************************************************************
    Sizes of OD arrays
*******************************************************************************/


/*******************************************************************************
    OD data declaration of all groups
*******************************************************************************/
typedef struct {
    struct {
        uint8_t highestSub_indexSupported;
        char family[8];
        char board[10];
    } x6000_moduleMCU;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t disabled;
        uint8_t TX_Port;
        uint8_t TX_Pin;
        uint8_t RX_Port;
        uint8_t RX_Pin;
        uint8_t RX_Pin;
    } x6200_transportCAN_1;
} Base_F4_RAM_t;

#ifndef Base_F4_ATTR_RAM
#define Base_F4_ATTR_RAM
#endif
extern Base_F4_ATTR_RAM Base_F4_RAM_t Base_F4_RAM;

#ifndef Base_F4_ATTR_OD
#define Base_F4_ATTR_OD
#endif
extern Base_F4_ATTR_OD OD_t *Base_F4;


/*******************************************************************************
    Object dictionary entries - shortcuts
*******************************************************************************/
#define Base_F4_ENTRY_H6000 &Base_F4->list[0]
#define Base_F4_ENTRY_H6200 &Base_F4->list[1]


/*******************************************************************************
    Object dictionary entries - shortcuts with names
*******************************************************************************/
#define Base_F4_ENTRY_H6000_moduleMCU &Base_F4->list[0]
#define Base_F4_ENTRY_H6200_transportCAN_1 &Base_F4->list[1]


/*******************************************************************************
    OD config structure
*******************************************************************************/
#ifdef CO_MULTIPLE_OD
#define Base_F4_INIT_CONFIG(config) {\
    (config).CNT_NMT = Base_F4_CNT_NMT;\
    (config).ENTRY_H1017 = NULL;\
    (config).CNT_HB_CONS = Base_F4_CNT_HB_CONS;\
    (config).CNT_ARR_1016 = 0;\
    (config).ENTRY_H1016 = NULL;\
    (config).CNT_EM = Base_F4_CNT_EM;\
    (config).ENTRY_H1001 = NULL;\
    (config).ENTRY_H1014 = NULL;\
    (config).ENTRY_H1015 = NULL;\
    (config).CNT_ARR_1003 = 0;\
    (config).ENTRY_H1003 = NULL;\
    (config).CNT_SDO_SRV = Base_F4_CNT_SDO_SRV;\
    (config).ENTRY_H1200 = NULL;\
    (config).CNT_SDO_CLI = Base_F4_CNT_SDO_CLI;\
    (config).ENTRY_H1280 = NULL;\
    (config).CNT_TIME = Base_F4_CNT_TIME;\
    (config).ENTRY_H1012 = NULL;\
    (config).CNT_SYNC = Base_F4_CNT_SYNC;\
    (config).ENTRY_H1005 = NULL;\
    (config).ENTRY_H1006 = NULL;\
    (config).ENTRY_H1007 = NULL;\
    (config).ENTRY_H1019 = NULL;\
    (config).CNT_RPDO = Base_F4_CNT_RPDO;\
    (config).ENTRY_H1400 = NULL;\
    (config).ENTRY_H1600 = NULL;\
    (config).CNT_TPDO = Base_F4_CNT_TPDO;\
    (config).ENTRY_H1800 = NULL;\
    (config).ENTRY_H1A00 = NULL;\
    (config).CNT_LEDS = 0;\
    (config).CNT_GFC = Base_F4_CNT_GFC;\
    (config).ENTRY_H1300 = NULL;\
    (config).CNT_SRDO = Base_F4_CNT_SRDO;\
    (config).ENTRY_H1301 = NULL;\
    (config).ENTRY_H1381 = NULL;\
    (config).ENTRY_H13FE = NULL;\
    (config).ENTRY_H13FF = NULL;\
    (config).CNT_LSS_SLV = 0;\
    (config).CNT_LSS_MST = 0;\
    (config).CNT_GTWA = 0;\
    (config).CNT_TRACE = 0;\
}
#endif

#endif /* Base_F4_H */
