#ifndef _DEV_EPAPER_H_
#define _DEV_EPAPER_H_

#define screen_epaper_FULL 0
#define screen_epaper_PART 1

#include "core/device.h"
#include "transport/spi.h"
/* Start of autogenerated OD types */
/* 0x9000: Screen Epaper 1
   E-ink screen with low power consumption and low update frequency */
typedef struct screen_epaper_properties {
    uint8_t parameter_count;
    uint16_t spi_index;
    uint8_t dc_port;
    uint8_t dc_pin;
    uint8_t cs_port;
    uint8_t cs_pin;
    uint8_t busy_port;
    uint8_t busy_pin;
    uint8_t reset_port;
    uint8_t reset_pin;
    uint16_t width;
    uint16_t height;
    uint16_t mode;
    uint8_t phase;
} screen_epaper_properties_t;
/* End of autogenerated OD types */

struct screen_epaper {
    device_t *device;
    screen_epaper_properties_t *properties;
    screen_epaper_properties_t *properties;
    transport_spi_t *spi;
    uint8_t resetting_phase;
    uint8_t initializing_phase;
};

extern device_methods_t screen_epaper_methods;

/* Start of autogenerated OD accessors */
#define SUBIDX_EPAPER_SPI_INDEX 0x1
#define SUBIDX_EPAPER_DC_PORT 0x2
#define SUBIDX_EPAPER_DC_PIN 0x3
#define SUBIDX_EPAPER_CS_PORT 0x4
#define SUBIDX_EPAPER_CS_PIN 0x5
#define SUBIDX_EPAPER_BUSY_PORT 0x6
#define SUBIDX_EPAPER_BUSY_PIN 0x7
#define SUBIDX_EPAPER_RESET_PORT 0x8
#define SUBIDX_EPAPER_RESET_PIN 0x9
#define SUBIDX_EPAPER_WIDTH 0x10
#define SUBIDX_EPAPER_HEIGHT 0x11
#define SUBIDX_EPAPER_MODE 0x12
#define SUBIDX_EPAPER_PHASE 0x13

ODR_t screen_epaper_set_spi_index(screen_epaper_t *epaper, uint16_t value); // 0x90XX01: epaper properties spi_index
uint16_t screen_epaper_get_spi_index(screen_epaper_t *epaper); // 0x90XX01: epaper properties spi_index
ODR_t screen_epaper_set_dc_port(screen_epaper_t *epaper, uint8_t value); // 0x90XX02: epaper properties dc_port
uint8_t screen_epaper_get_dc_port(screen_epaper_t *epaper); // 0x90XX02: epaper properties dc_port
ODR_t screen_epaper_set_dc_pin(screen_epaper_t *epaper, uint8_t value); // 0x90XX03: epaper properties dc_pin
uint8_t screen_epaper_get_dc_pin(screen_epaper_t *epaper); // 0x90XX03: epaper properties dc_pin
ODR_t screen_epaper_set_cs_port(screen_epaper_t *epaper, uint8_t value); // 0x90XX04: epaper properties cs_port
uint8_t screen_epaper_get_cs_port(screen_epaper_t *epaper); // 0x90XX04: epaper properties cs_port
ODR_t screen_epaper_set_cs_pin(screen_epaper_t *epaper, uint8_t value); // 0x90XX05: epaper properties cs_pin
uint8_t screen_epaper_get_cs_pin(screen_epaper_t *epaper); // 0x90XX05: epaper properties cs_pin
ODR_t screen_epaper_set_busy_port(screen_epaper_t *epaper, uint8_t value); // 0x90XX06: epaper properties busy_port
uint8_t screen_epaper_get_busy_port(screen_epaper_t *epaper); // 0x90XX06: epaper properties busy_port
ODR_t screen_epaper_set_busy_pin(screen_epaper_t *epaper, uint8_t value); // 0x90XX07: epaper properties busy_pin
uint8_t screen_epaper_get_busy_pin(screen_epaper_t *epaper); // 0x90XX07: epaper properties busy_pin
ODR_t screen_epaper_set_reset_port(screen_epaper_t *epaper, uint8_t value); // 0x90XX08: epaper properties reset_port
uint8_t screen_epaper_get_reset_port(screen_epaper_t *epaper); // 0x90XX08: epaper properties reset_port
ODR_t screen_epaper_set_reset_pin(screen_epaper_t *epaper, uint8_t value); // 0x90XX09: epaper properties reset_pin
uint8_t screen_epaper_get_reset_pin(screen_epaper_t *epaper); // 0x90XX09: epaper properties reset_pin
ODR_t screen_epaper_set_width(screen_epaper_t *epaper, uint16_t value); // 0x90XX0a: epaper properties width
uint16_t screen_epaper_get_width(screen_epaper_t *epaper); // 0x90XX0a: epaper properties width
ODR_t screen_epaper_set_height(screen_epaper_t *epaper, uint16_t value); // 0x90XX0b: epaper properties height
uint16_t screen_epaper_get_height(screen_epaper_t *epaper); // 0x90XX0b: epaper properties height
ODR_t screen_epaper_set_mode(screen_epaper_t *epaper, uint16_t value); // 0x90XX0c: epaper properties mode
uint16_t screen_epaper_get_mode(screen_epaper_t *epaper); // 0x90XX0c: epaper properties mode
ODR_t screen_epaper_set_phase(screen_epaper_t *epaper, uint8_t value); // 0x90XX0d: epaper properties phase
uint8_t screen_epaper_get_phase(screen_epaper_t *epaper); // 0x90XX0d: epaper properties phase
/* End of autogenerated OD accessors */
#endif