#ifndef _DEV_EPAPER_H_
#define _DEV_EPAPER_H_

#define screen_epaper_FULL 0
#define screen_epaper_PART 1

#include "core/device.h"
#include "transport/spi.h"
/* Start of autogenerated OD types */
/* 0x7000: Screen Epaper 1
   E-ink screen with low power consumption and low update frequency */
typedef struct screen_epaper_config {
    uint8_t parameter_count;
    int16_t disabled;
    uint16_t spi_index;
    uint8_t dc_port;
    uint8_t dc_pin;
    uint8_t cs_port;
    uint8_t cs_pin;
    uint8_t busy_port;
    uint8_t busy_pin;
    uint8_t reset_port;
    uint8_t reset_pin;
    uint16_t width;
    uint16_t height;
    uint16_t mode;
} screen_epaper_config_t;
/* End of autogenerated OD types */

struct screen_epaper {
    device_t *device;
    screen_epaper_config_t *config;
    screen_epaper_values_t *values;
    transport_spi_t *spi;
    uint8_t resetting_phase;
    uint8_t initializing_phase;
};

extern device_methods_t screen_epaper_methods;

/* Start of autogenerated OD accessors */
#define SUBIDX_EPAPER_DISABLED 0x1
#define SUBIDX_EPAPER_SPI_INDEX 0x2
#define SUBIDX_EPAPER_DC_PORT 0x3
#define SUBIDX_EPAPER_DC_PIN 0x4
#define SUBIDX_EPAPER_CS_PORT 0x5
#define SUBIDX_EPAPER_CS_PIN 0x6
#define SUBIDX_EPAPER_BUSY_PORT 0x7
#define SUBIDX_EPAPER_BUSY_PIN 0x8
#define SUBIDX_EPAPER_RESET_PORT 0x9
#define SUBIDX_EPAPER_RESET_PIN 0x10
#define SUBIDX_EPAPER_WIDTH 0x11
#define SUBIDX_EPAPER_HEIGHT 0x12
#define SUBIDX_EPAPER_MODE 0x13

/* End of autogenerated OD accessors */
#endif