#ifndef _DEV_EPAPER_H_
#define _DEV_EPAPER_H_


#define device_epaper_FULL			0
#define device_epaper_PART			1

#include "devices/devices.h"
#include "modules/spi.h"
/* Start of autogenerated OD types */
/* 0x7500: Device Epaper 1
   E-ink screen with low power consumption and low update frequency */
typedef struct {
    int16_t disabled;
    uint16_t spi_index;
    uint8_t dc_port;
    uint8_t dc_pin;
    uint8_t cs_port;
    uint8_t cs_pin;
    uint8_t busy_port;
    uint8_t busy_pin;
    uint8_t reset_port;
    uint8_t reset_pin;
    uint16_t width;
    uint16_t height;
    uint16_t mode;
} device_epaper_config_t;

/* 0x8500: Device Values Epaper 1null */
typedef struct {
    int16_t image_buffer;
    int16_t render_count;
} device_epaper_values_t;
/* End of autogenerated OD types */

typedef struct {
    device_t *device;
    device_epaper_config_t *config;
    device_epaper_values_t *values;
    module_spi_t *spi;
    uint8_t resetting_phase;
    uint8_t initializing_phase;
} device_epaper_t;

extern device_callbacks_t device_epaper_callbacks;

/* Start of autogenerated OD accessors */
#define SUBIDX_EPAPER_DISABLED 0x1
#define SUBIDX_EPAPER_SPI_INDEX 0x2
#define SUBIDX_EPAPER_DC_PORT 0x3
#define SUBIDX_EPAPER_DC_PIN 0x4
#define SUBIDX_EPAPER_CS_PORT 0x5
#define SUBIDX_EPAPER_CS_PIN 0x6
#define SUBIDX_EPAPER_BUSY_PORT 0x7
#define SUBIDX_EPAPER_BUSY_PIN 0x8
#define SUBIDX_EPAPER_RESET_PORT 0x9
#define SUBIDX_EPAPER_RESET_PIN 0x10
#define SUBIDX_EPAPER_WIDTH 0x11
#define SUBIDX_EPAPER_HEIGHT 0x12
#define SUBIDX_EPAPER_MODE 0x13
#define SUBIDX_EPAPER_IMAGE_BUFFER 0x1
#define SUBIDX_EPAPER_RENDER_COUNT 0x2

ODR_t device_epaper_set_image_buffer(device_epaper_t *epaper, int16_t value); // 0x85XX01: epaper values image_buffer
int16_t device_epaper_get_image_buffer(device_epaper_t *epaper); // 0x85XX01: epaper values image_buffer
ODR_t device_epaper_set_render_count(device_epaper_t *epaper, int16_t value); // 0x85XX02: epaper values render_count
int16_t device_epaper_get_render_count(device_epaper_t *epaper); // 0x85XX02: epaper values render_count
/* End of autogenerated OD accessors */
#endif