#include "mothership.h"

/* Start of autogenerated OD accessors */
/* End of autogenerated OD accessors */

static ODR_t OD_write_app_mothership_property(OD_stream_t *stream, const void *buf, OD_size_t count,
                                            OD_size_t *countWritten) {
    app_mothership_t *mothership = stream->object;
    (void)mothership;
    ODR_t result = OD_writeOriginal(stream, buf, count, countWritten);
    
    return result;
}


static int app_mothership_validate(OD_entry_t *config_entry) {
    app_mothership_config_t *config = (app_mothership_config_t *)OD_getPtr(config_entry, 0x01, 0, NULL);
    (void)config;
    if (false) {
        return CO_ERROR_OD_PARAMETERS;
    }
    return 0;
}

static int app_mothership_construct(app_mothership_t *mothership, device_t *device) {
    mothership->device = device;
    mothership->config = (app_mothership_config_t *)OD_getPtr(device->config, 0x01, 0, NULL);
    return mothership->config->disabled;
}

static int app_mothership_start(app_mothership_t *mothership) {
    (void)mothership;
    return 0;
}

static int app_mothership_stop(app_mothership_t *mothership) {
    (void)mothership;
    return 0;
}

static int app_mothership_pause(app_mothership_t *mothership) {
    (void)mothership;
    return 0;
}

static int app_mothership_resume(app_mothership_t *mothership) {
    (void)mothership;
    return 0;
}

static int app_mothership_link(app_mothership_t *mothership) {
    device_link(mothership->device, (void **)&mothership->mcu, 0x6000, NULL);
    device_link(mothership->device, (void **)&mothership->canopen, 0x6010, NULL);
    return 0;
}

static int app_mothership_phase(app_mothership_t *mothership, device_phase_t phase) {
    (void)mothership;
    (void)phase;
    return 0;
}

// Initialize all devices of all types found in OD
// If devices is NULL, it will only count the devices
size_t app_mothership_enumerate_devices(app_t *app, OD_t *od, device_t *destination) {
    size_t count = 0;
    count += devices_enumerate_type(app, od, APP, &app_mothership_callbacks, sizeof(app_mothership_t), destination, count);
    count += devices_enumerate_type(app, od, SYSTEM_MCU, &system_mcu_callbacks, sizeof(system_mcu_t), destination, count);
    count += devices_enumerate_type(app, od, MODULE_ADC, &module_adc_callbacks, sizeof(module_adc_t), destination, count);
    count += devices_enumerate_type(app, od, TRANSPORT_CAN, &transport_can_callbacks, sizeof(transport_can_t), destination, count);
    //count += devices_enumerate_type(app, od, TRANSPORT_SPI, &transport_spi_callbacks, sizeof(transport_spi_t), destination, count);
    //count += devices_enumerate_type(MODULE_USART, &transport_usart_callbacks, sizeof(transport_usart_t), destination, count);
    //count += devices_enumerate_type(app, od, TRANSPORT_I2C, &transport_i2c_callbacks, sizeof(transport_i2c_t), destination, count);
    //count += devices_enumerate_type(app, od, DEVICE_CIRCUIT, &device_circuit_callbacks, sizeof(device_circuit_t), destination, count);
    //count += devices_enumerate_type(app, OD, SCREEN_EPAPER, &screen_epaper_callbacks, sizeof(screen_epaper_t), destination, count);
    //count += devices_enumerate_type(app, od, INPUT_SENSOR, &input_sensor_callbacks, sizeof(input_sensor_t), destination, count);
    return count;
}


device_callbacks_t app_mothership_callbacks = {.validate = app_mothership_validate,
                                             .construct = (int (*)(void *, device_t *))app_mothership_construct,
                                             .link = (int (*)(void *))app_mothership_link,
                                             .start = (int (*)(void *))app_mothership_start,
                                             .stop = (int (*)(void *))app_mothership_stop,
                                             .pause = (int (*)(void *))app_mothership_pause,
                                             .resume = (int (*)(void *))app_mothership_resume,
                                             //.accept = (int (*)(void *, device_t *device, void *channel))app_mothership_accept,
                                             .phase = (int (*)(void *, device_phase_t phase))app_mothership_phase,
                                             .write_values = OD_write_app_mothership_property};
