#ifndef INC_APP_MOTHERSHIP
#define INC_APP_MOTHERSHIP

#ifdef __cplusplus
extern "C" {
#endif

#include "core/app.h"
#include "system/mcu.h"
#include "system/canopen.h"
/* Start of autogenerated OD types */
typedef struct {
    uint8_t parameter_count;
    uint32_t timer_index;
    uint32_t mcu_index;
    uint32_t canopen_index;
} app_mothership_config_t;
/* End of autogenerated OD types */

typedef struct app_mothership {
    device_t *device;
    size_t device_count;
    OD_t *dictionary;
    app_mothership_config_t *config;
    //app_values_t *values;
    app_threads_t *threads;
    system_mcu_t *mcu;
    system_canopen_t *canopen;
    module_timer_t *timer;
    app_thread_t *current_thread;
} app_mothership_t;


extern device_methods_t app_mothership_methods;

size_t app_mothership_enumerate_devices(app_t *app, OD_t *od, device_t *destination);

/* Start of autogenerated OD accessors */
/* End of autogenerated OD accessors */

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif