#ifndef INC_DEV_BLANK
#define INC_DEV_BLANK

#ifdef __cplusplus
extern "C" {
#endif

#include "core/device.h"

/* Start of autogenerated OD types */
typedef struct {
    uint8_t phase;
} device_blank_properties_t;
/* End of autogenerated OD types */

struct device_blank {
    device_t *device;
    device_blank_properties_t *properties;
};


extern device_class_t device_blank_class;

/* Start of autogenerated OD accessors */
/* End of autogenerated OD accessors */

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif