#ifndef INC_DEV_BLANK
#define INC_DEV_BLANK

#ifdef __cplusplus
extern "C" {
#endif

#include "core/device.h"

/* Start of autogenerated OD types */
typedef struct {
    int16_t disabled;
} device_blank_config_t;
/* End of autogenerated OD types */

typedef struct {
    device_t *device;
    device_blank_config_t *config;
} device_blank_t;


extern device_methods_t device_blank_methods;

/* Start of autogenerated OD accessors */
/* End of autogenerated OD accessors */

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif