#ifndef INC_DEV_WINBOND
#define INC_DEV_WINBOND

#ifdef __cplusplus
extern "C" {
#endif

#include "core/device.h"

#define W25_CMD_MANUF_DEVICE 0x90
#define W25_CMD_READ_SR1	0x05

#define W25_SR1_BUSY		0x01

/* Start of autogenerated OD types */
/* 0x6320: Storage Winbond
   Winbond flash storage device over SPI */
typedef struct {
    int16_t disabled;
    uint16_t spi_index;
    uint16_t page_size;
    uint16_t size;
} storage_winbond_config_t;
/* End of autogenerated OD types */

typedef struct {
    device_t *device;
    storage_winbond_config_t *config;
    device_t *spi;
    app_task_t *task;
} storage_winbond_t;


extern device_callbacks_t storage_winbond_callbacks;

/* Start of autogenerated OD accessors */
#define SUBIDX_WINBOND_DISABLED 0x1
#define SUBIDX_WINBOND_SPI_INDEX 0x2
#define SUBIDX_WINBOND_PAGE_SIZE 0x3
#define SUBIDX_WINBOND_SIZE 0x4

/* End of autogenerated OD accessors */

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif