#ifndef CO_DEV_USART_H
#define CO_DEV_USART_H

#ifdef __cplusplus
extern "C" {
#endif

#include "devices.h"
#include <libopencm3/stm32/usart.h>

#define USART_RX_BUFFER_SIZE 64

/* Start of autogenerated OD types */
/* 0x6140: undefinedundefined */
typedef struct {
    int16_t disabled;
    uint8_t dma_rx_unit;
    uint8_t dma_rx_stream;
    uint8_t dma_rx_channel;
    uint8_t dma_rx_buffer_size;
    uint8_t dma_tx_unit;
    uint8_t dma_tx_stream;
    uint8_t dma_tx_channel;
    uint32_t baudrate;
    uint8_t databits;
} transport_usart_config_t;
/* End of autogenerated OD types */

typedef struct {
    device_t *device;
    transport_usart_config_t *config;
    uint32_t clock;
    uint32_t address;
    uint32_t dma_tx_address;
    uint32_t dma_rx_address;
    device_t *target_device;
    void *target_argument;

    uint8_t *dma_rx_buffer;
} transport_usart_t;

extern device_callbacks_t transport_usart_callbacks;

int transport_usart_send(transport_usart_t *usart, char *data, int size);


/* Start of autogenerated OD accessors */
#define SUBIDX_USART_DISABLED 0x1
#define SUBIDX_USART_DMA_RX_UNIT 0x2
#define SUBIDX_USART_DMA_RX_STREAM 0x3
#define SUBIDX_USART_DMA_RX_CHANNEL 0x4
#define SUBIDX_USART_DMA_RX_BUFFER_SIZE 0x5
#define SUBIDX_USART_DMA_TX_UNIT 0x6
#define SUBIDX_USART_DMA_TX_STREAM 0x7
#define SUBIDX_USART_DMA_TX_CHANNEL 0x8
#define SUBIDX_USART_BAUDRATE 0x9
#define SUBIDX_USART_DATABITS 0x10

/* End of autogenerated OD accessors */

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif