#ifndef INC_ENUMS
#define INC_ENUMS
#include "core/types.h"
// defined in ./src/core/actor.h
char* get_actor_phase_name (uint32_t v);
// defined in ./src/core/actor.h
char* get_actor_type_name (uint32_t v);
// defined in ./src/core/app.h
char* get_app_signal_name (uint32_t v);
// defined in ./src/core/app.h
char* get_app_properties_properties_name (uint32_t v);
// defined in ./src/core/event.h
char* get_app_event_type_name (uint32_t v);
// defined in ./src/core/event.h
char* get_app_event_status_name (uint32_t v);
// defined in ./src/core/task.h
char* get_app_task_signal_name (uint32_t v);
// defined in ./src/device/circuit.h
char* get_device_circuit_properties_properties_name (uint32_t v);
// defined in ./src/indicator/led.h
char* get_indicator_led_properties_properties_name (uint32_t v);
// defined in ./src/input/sensor.h
char* get_input_sensor_properties_properties_name (uint32_t v);
// defined in ./src/lib/vpool.h
char* get_vpool_trunc_name (uint32_t v);
// defined in ./src/module/adc.h
char* get_module_adc_properties_properties_name (uint32_t v);
// defined in ./src/module/timer.h
char* get_module_timer_properties_properties_name (uint32_t v);
// defined in ./src/screen/epaper.h
char* get_screen_epaper_properties_properties_name (uint32_t v);
// defined in ./src/storage/w25.h
char* get_w25_commands_name (uint32_t v);
// defined in ./src/storage/w25.h
char* get_storage_w25_properties_properties_name (uint32_t v);
// defined in ./src/system/canopen.h
char* get_system_canopen_properties_properties_name (uint32_t v);
// defined in ./src/system/mcu.h
char* get_system_mcu_properties_properties_name (uint32_t v);
// defined in ./src/transport/can.h
char* get_transport_can_properties_properties_name (uint32_t v);
// defined in ./src/transport/i2c.h
char* get_transport_i2c_properties_properties_name (uint32_t v);
// defined in ./src/transport/modbus.h
char* get__name (uint32_t v);
// defined in ./src/transport/modbus.h
char* get_transport_modbus_properties_properties_name (uint32_t v);
// defined in ./src/transport/spi.h
char* get_transport_spi_properties_properties_name (uint32_t v);
// defined in ./src/transport/usart.h
char* get_transport_usart_properties_properties_name (uint32_t v);
#endif