#include "mcu.h"

/* Start of autogenerated OD accessors */
OD_ACCESSORS(module, mcu, values, cpu_temperature, SUBIDX_MCU_CPU_TEMPERATURE, int8_t, i8) /* 0x80XX01: values */
OD_ACCESSORS(module, mcu, values, startup_time, SUBIDX_MCU_STARTUP_TIME, uint64_t, u64) /* 0x80XX02: values */
/* End of autogenerated OD accessors */

static ODR_t OD_write_module_mcu_property(OD_stream_t *stream, const void *buf, OD_size_t count, OD_size_t *countWritten) {
    module_mcu_t *mcu = stream->object;
    (void)mcu;
    ODR_t result = OD_writeOriginal(stream, buf, count, countWritten);
    return result;
}

static int module_mcu_validate(OD_entry_t *config_entry) {
    module_mcu_config_t *config = (module_mcu_config_t *)OD_getPtr(config_entry, 0x01, 0, NULL);
    (void)config;
    if (false) {
        return CO_ERROR_OD_PARAMETERS;
    }
    return 0;
}

static int module_mcu_construct(module_mcu_t *mcu, device_t *device) {
    mcu->device = device;
    mcu->config = (module_mcu_config_t *)OD_getPtr(device->config, 0x01, 0, NULL);
    return mcu->config->disabled;
}

static int module_mcu_start(module_mcu_t *mcu) {
#if defined(STM32F1)
    rcc_clock_setup_pll(&rcc_hsi_configs[RCC_CLOCK_HSE8_72MHZ]);
#elif defined(STM32F4)
    rcc_clock_setup_pll(&rcc_hse_8mhz_3v3[RCC_CLOCK_3V3_168MHZ]);
#endif
    return 0;
}

static int module_mcu_stop(module_mcu_t *mcu) {
    (void)mcu;
    return 0;
}

static int module_mcu_pause(module_mcu_t *mcu) {
    (void)mcu;
    return 0;
}

static int module_mcu_resume(module_mcu_t *mcu) {
    (void)mcu;
    return 0;
}

static int module_mcu_tick(module_mcu_t *mcu, uint32_t time_passed, uint32_t *next_tick) {
    (void)mcu;
    (void)time_passed;
    (void)next_tick;
    return 0;
}

static int module_mcu_link(module_mcu_t *mcu) {
    (void)mcu;
    return device_link(mcu->device, (void **)&mcu->storage, mcu->config->storage_index, NULL);
}

static int module_mcu_phase(module_mcu_t *mcu, device_phase_t phase) {
    (void)mcu;
    (void)phase;
    return 0;
}

device_callbacks_t module_mcu_callbacks = {.validate = module_mcu_validate,
                                           .construct = (int (*)(void *, device_t *))module_mcu_construct,
                                           .link = (int (*)(void *))module_mcu_link,
                                           .start = (int (*)(void *))module_mcu_start,
                                           .stop = (int (*)(void *))module_mcu_stop,
                                           .pause = (int (*)(void *))module_mcu_pause,
                                           .resume = (int (*)(void *))module_mcu_resume,
                                           .tick = (int (*)(void *, uint32_t time_passed, uint32_t *next_tick))module_mcu_tick,
                                           //.accept = (int (*)(void *, device_t *device, void *channel))module_mcu_accept,
                                           .phase = (int (*)(void *, device_phase_t phase))module_mcu_phase,
                                           .write_values = OD_write_module_mcu_property};
