#ifndef INC_DEV_SENSOR
#define INC_DEV_SENSOR

#ifdef __cplusplus
extern "C" {
#endif

#include "core/device.h"
#include "module/adc.h"

/* Start of autogenerated OD types */
/* 0x8000: Input Sensor 1
   A sensor that measures a single analog value (i.e. current meter, tank level meter) */
typedef struct input_sensor_properties {
    uint8_t parameter_count;
    uint16_t disabled; // Values other than zero will prevent device from initializing 
    uint8_t port; // Analog GPIO port (1 for A, 2 for B, etc), required 
    uint8_t pin; // Analog GPIO pin, required 
    uint16_t adc_index; // OD Index of ADC unit that will take measurements, must play well with the gpio setup 
    uint8_t adc_channel; // ADC channel unique for unit to handle measurements 
    uint8_t phase; // Current phase of a device (one of values in DEVICE_PHASE enum) 
} input_sensor_properties_t;
/* End of autogenerated OD types */

struct input_sensor {
    device_t *device;
    input_sensor_properties_t *properties;
    device_t *target_device;
    void *target_argument;
    module_adc_t *adc;
};


extern device_class_t input_sensor_class;

/* Start of autogenerated OD accessors */
typedef enum input_sensor_properties_properties {
  INPUT_SENSOR_DISABLED = 0x1,
  INPUT_SENSOR_PORT = 0x2,
  INPUT_SENSOR_PIN = 0x3,
  INPUT_SENSOR_ADC_INDEX = 0x4,
  INPUT_SENSOR_ADC_CHANNEL = 0x5,
  INPUT_SENSOR_PHASE = 0x6
} input_sensor_properties_properties_t;

#define input_sensor_set_phase(sensor, value) OD_set_u8(sensor->device->properties, INPUT_SENSOR_PHASE, value, false)
#define input_sensor_get_phase(sensor) *((uint8_t *) OD_getPtr(sensor->device->class->properties, INPUT_SENSOR_PHASE, 0, NULL))
/* End of autogenerated OD accessors */

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif