#include "sensor.h"

/* Start of autogenerated OD accessors */
OD_ACCESSORS(input, sensor, values, disabled, SUBIDX_SENSOR_DISABLED, uint16_t, u16) /* 0x88XX01: values */
OD_ACCESSORS(input, sensor, values, port, SUBIDX_SENSOR_PORT, uint8_t, u8) /* 0x88XX02: values */
OD_ACCESSORS(input, sensor, values, pin, SUBIDX_SENSOR_PIN, uint8_t, u8) /* 0x88XX03: values */
OD_ACCESSORS(input, sensor, values, adc_index, SUBIDX_SENSOR_ADC_INDEX, uint16_t, u16) /* 0x88XX04: values */
OD_ACCESSORS(input, sensor, values, adc_channel, SUBIDX_SENSOR_ADC_CHANNEL, uint8_t, u8) /* 0x88XX05: values */
/* End of autogenerated OD accessors */

static ODR_t OD_write_input_sensor_property(OD_stream_t *stream, const void *buf, OD_size_t count,
                                             OD_size_t *countWritten) {
    input_sensor_t *sensor = stream->object;
    (void)sensor;
    ODR_t result = OD_writeOriginal(stream, buf, count, countWritten);
    return result;
}

static int input_sensor_validate(OD_entry_t *config_entry) {
    input_sensor_config_t *config = (input_sensor_config_t *)OD_getPtr(config_entry, 0x01, 0, NULL);
    (void)config;
    if (false) {
        return CO_ERROR_OD_PARAMETERS;
    }
    return 0;
}

static int input_sensor_phase_constructing(input_sensor_t *sensor, device_t *device) {
    sensor->config = (input_sensor_config_t *)OD_getPtr(device->config, 0x01, 0, NULL);
    return sensor->config->disabled;
}

static int input_sensor_phase_starting(input_sensor_t *sensor) {
    (void)sensor;
    return 0;
}

static int input_sensor_phase_stoping(input_sensor_t *sensor) {
    (void)sensor;
    return 0;
}

static int input_sensor_phase_pausing(input_sensor_t *sensor) {
    (void)sensor;
    return 0;
}

static int input_sensor_phase_resuming(input_sensor_t *sensor) {
    (void)sensor;
    return 0;
}


// pass over adc value to the linked device
static int input_sensor_receive(input_sensor_t *sensor, device_t *device, void *value, void *channel) {
    (void) channel; /*unused*/
    if (sensor->adc->device == device) {
        device_send(sensor->device, sensor->target_device, value, sensor->target_argument);
    }
    return 0;
}

static int input_sensor_phase_linking(input_sensor_t *sensor) {
    return device_phase_linking(sensor->device, (void **)&sensor->adc, sensor->config->adc_index, (void *) (uint32_t) sensor->config->adc_channel);
}

static int input_sensor_accept(input_sensor_t *sensor, device_t *target, void *argument) {
    sensor->target_device = target;
    sensor->target_argument = argument;
    return 0;
}

static int input_sensor_phase(input_sensor_t *sensor, device_phase_t phase) {
    (void)sensor;
    (void)phase;
    return 0;
}

device_methods_t input_sensor_methods = {
    .validate = input_sensor_validate,
    .phase_constructing = (app_signal_t (*)(void *, device_t *))input_sensor_phase_constructing,
    .phase_linking = (app_signal_t (*)(void *))input_sensor_phase_linking,
    .phase_starting = (app_signal_t (*)(void *))input_sensor_phase_starting,
    .phase_stoping = (app_signal_t (*)(void *))input_sensor_phase_stoping,
    .phase_pausing = (app_signal_t (*)(void *))input_sensor_phase_pausing,
    .phase_resuming = (app_signal_t (*)(void *))input_sensor_phase_resuming,
    .phase_linking = (app_signal_t (*)(void *, device_t *device, void *channel))input_sensor_accept,
    .callback_value = (app_signal_t (*)(void *, device_t *device, void *value, void *channel))input_sensor_receive,
    .callback_phase = (app_signal_t (*)(void *, device_phase_t phase))input_sensor_phase,
    .write_values = OD_write_input_sensor_property};
